template_enno:
    resource: "@TemplateEnnoBundle/Controller/"
    type:     annotation
    prefix:   /

template_lonely:
    resource: "@TemplateLonelyBundle/Controller/"
    type:     annotation
    prefix:   /
